### ISSUE TITLE
K3s Cluster Node(s) Upgrade

### ISSUE THREAD

**Issue by nicklausbrown** [xunleii/terraform-module-k3s#132]
Hello @xunleii,

I did not see a discussions area for the repo, so I will ask my question here as it seems undocumented. Can this terraform module appropriately upgrade a k3s cluster similar to what is described in the "manual" part of the documentation [here](https://docs.k3s.io/upgrades/manual). If not is there another recommended way to handle version upgrades gracefully?

Otherwise, thanks for open sourcing this project. I haven't finished implementing it yet, but it makes operations a lot easier.

**Comment by xunleii** [comment]
Hi @nicklausbrown,

No, I have never considered implementing this. Even if `k3d` is not the right tool for the job _(`k3d` and this module do the same job, i.e. provision a K3s cluster)_, using docker to start X nodes with an SSH server and run this module on them seems like a good idea.

Currently, there's an end-to-end test using a real Hetzner Cloud instances (with my own money), but it's not run manually and doesn't work properly on fork (because it requires some secrets to push comment on PR). So actually, using a local docker container could help me a lot to run these tests on every PR.

Thanks for your suggestion, I'll try to implement this feature this week-end.

_NOTE: here is the workflow: https://github.com/xunleii/terraform-module-k3s/blob/master/.github/workflows/terraform.plan.yaml_

**Comment by xunleii** [comment]
Hi @nicklausbrown,

I've just checked (and tested) and here the upgrade process using this module :

1. Downloads the latest installation script from Github
2. Reruns the installation script with the new k3s release
4. Waits until the node is ready

I therefore confirm that this module follows [the official upgrade procedure](https://docs.k3s.io/upgrades/manual#upgrade-k3s-using-the-installation-script) by using the official installation script.

However, a word about the upgrade procedure wouldn't go amiss, thanks for bringing it up.

**Comment by laurentiusoica** [comment]
@xunleii During the upgrade process, I noticed that all the nodes get upgraded simultaneously. This leads to a situation where all the master nodes are unavailable for a certain duration. Is there an option to perform the upgrades one after another instead?

**Comment by xunleii** [comment]
Yep, thank you for that. Indeed, there is no mechanism to have a non-parallel update. I did it because there is little downtime _(in most cases_) and I didn't want to make this module too complicated.

However, if it's something really blocking, I can make the first server serve as a dependency for the others. With this, there will always be at least one server available to communicate with, but I'll also have to find out if there's a risk of split brain N-1 servers updating at the same time.

**Comment by laurentiusoica** [comment]
Not exactly a blocker but it breaks the HA guarantees in case of an HA setup. An option to have an one node at a time upgrade would be great.

**Comment by laurentiusoica** [comment]
@xunleii What are your thoughts on introducing a feature flag for sequential execution that would, when enabled, enforce a sequential creation of servers and agents by adding a depends_on attribute to the preceding resource when the index is greater than 0? When this flag is disabled, which would be the default setting, the current behavior would be maintained.

**Comment by xunleii** [comment]
> @xunleii What are your thoughts on introducing a feature flag for sequential execution that would, when enabled, enforce a sequential creation of servers and agents by adding a depends_on attribute to the preceding resource when the index is greater than 0? When this flag is disabled, which would be the default setting, the current behavior would be maintained.

I agree with you, it can be very useful.
Unfortunately, I don't see how to implement it on Terraform; because it's a module and not a provider, I'm very limited on what I can do. For example here, node resources are created by a loop and all are made in parallel. I don't see how I can make it sequential instead 😞
