### ISSUE TITLE
Consider Integration Testing with k3d

### ISSUE THREAD

**Issue by nicklausbrown** [xunleii/terraform-module-k3s#133]
@xunleii 

Have you considered setting up github actions to run the terraform module against a k3d cluster which could be installed on a single github actions agent? This way it would be possible to verify functionality on each pull request. I'm writing my own tool in python for managing k3s lifecycle on a home cluster, but I would prefer terraform in the longterm since it would be easier to maintain.

**Comment by xunleii** [comment]
Hi @nicklausbrown,

No, I have never considered implementing this. Even if `k3d` is not the right tool for the job _(`k3d` and this module do the same job, i.e. provision a K3s cluster)_, using docker to start X nodes with an SSH server and run this module on them seems like a good idea.

Currently, there's an end-to-end test using a real Hetzner Cloud instances (with my own money), but it's not run manually and doesn't work properly on fork (because it requires some secrets to push comment on PR). So actually, using a local docker container could help me a lot to run these tests on every PR.

Thanks for your suggestion, I'll try to implement this feature this week-end.

_NOTE: here is the workflow: https://github.com/xunleii/terraform-module-k3s/blob/master/.github/workflows/terraform.plan.yaml_

**Comment by nicklausbrown** [comment]
I'm glad this was helpful and curious if you made any progress?

You are correct that you would want to do your own custom container work for the tests, I thought k3d could be an inspiration. I saw your original testing on the cloud and thought this might help save some headache and money 😄 

Additionally, my tool does cluster deletion too which might be something to consider if you haven't implemented the deleting operations for terraform. I didn't check this though, perhaps you already have!

**Comment by xunleii** [comment]
Unfortunately, I underestimated the time needed to run a "full" compatible OS in order to install k3s on it 😅 (k3d uses an preinstalled k3s on a scratch image) and I didn't have enough time for now to continue. I have some plan but need more time to implement it.

But I will probably find some time in the next weeks to implement it (I hope at least).
