### ISSUE TITLE
When generate_ca_certificates = false, module does not export any kubeconfig

### ISSUE THREAD

**Issue by alita1991** [xunleii/terraform-module-k3s#143]
Hi,

When provisioning k3s with generate_ca_certificates = false, I noticed that the kubeconfig file is not available anymore. Is there a reason for not exporting it for this particular scenario?

Thanks

**Comment by alita1991** [comment]
Hi @xunleii, thanks for your quick response, is pretty surprising that terraform does not offer at least the basic functionality  like ssh/scp, which is required in many scenarios, including the one where you need to get the logs for debugging purposes.

I guess we can close this ticket for now, and wait until we have support from terraform.

Thanks

**Comment by xunleii** [comment]
I think they made this choice because Terraform is not a "provisioning" tool like Ansible that do things directly on instances but more a tool to interface all cloud/API providers in a same and reproducible manner.

To be honest, this module is a bit "crappy" for Terraform because it uses Terraform like Ansible to install k3s with the power of TF state _(and mostly because I don't like Ansible 🙄)_.

Also, if you already use Ansible, maybe the [k3s-ansible](https://github.com/k3s-io/k3s-ansible) may suit your needs better.
