### ISSUE TITLE
Support for K3S AirGap deployments

### ISSUE THREAD

**Issue by lsoica** [xunleii/terraform-module-k3s#155]
The current implementation of the module deploys K3S clusters as long as the data center is connected to the internet.

It would be a nice addition to extend the functionality with K3S deployments in AirGap environments where one cannot download files from the internet but relies on the files being preset on the execution box: https://docs.k3s.io/installation/airgap

**Comment by xunleii** [comment]
I've never installed k3s in an air-gap environment, but from what I've read, this is a very specific case where the installation may depend on the OS; an air-gap installation on a Debian will not be the same as on a Fedora or Arch. What's more, there's a risk that people will open problems if something doesn't work because the machine hasn't been properly configured and not because of the module itself. 

I don't want to add more complexity to this module (which already exploits some _Terraform tricks_) to allow this. However, if you really need it, it is already possible to launch the installation with `INSTALL_K3S_SKIP_DOWNLOAD=true` via the `k3s_install_env_vars` variable; you just need to configure the machine and push all the images before running this module.
