### ISSUE TITLE
:unicorn: Add Certificate data as outputs

### ISSUE THREAD

**Issue by martin31821** [xunleii/terraform-module-k3s#182]
### :fire: What happened?

Provisioned k3s cluster, tried to bootstrap k8s terraform provider with the outputs of this module, but theres no way to directly set the kubeconfig.

### :+1: What did you expect to happen?

I'd like to add three outputs: Cluster-CA Pem, User Certificate and User Key, to bootstrap the k8s provider.

### :mag: How can we reproduce the issue?

- Create TF state
- Try to create a k8s provider that's running against the k3s
- No way to do it.

### :wrench: Module version

3.4.0

### :wrench: Terraform version

1.8

### :wrench: Terraform providers

--

**Comment by xunleii** [comment]
Hi @martin31821, sorry, I didn't seen your issue. I think this project lacks of documentation because everything is already present into the `kubernetes` output :

- Cluster-CA Pem → `kubernetes.cluster_ca_certificate`
- User Certificate → `kubernetes.client_certificate`
- User Key → `kubernetes.client_key`
